title: Development Lab
author: Thomas Piekarski
email: t.piekarski@deloquencia.de
description: >- 
  A laboratory and a sandbox as well for tips, prototyping and learning of ideas, concepts and technologies
  in software development.
baseurl: ""
url: "https://tpiekarski.github.io"
timezone: Europe/Berlin
encoding: utf-8
incremental: false

twitter_username: deloquencia
github_username: tpiekarski

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - .gitignore
  - homepage.code-workspace
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
